### ISSUE TITLE
Meta Issue for tracking todos

### ISSUE THREAD

**Issue by micahgodbolt** [micahgodbolt/fluid-react-starter#1]
## general

- [x] #2
- [x] create createNewDocument - returns document URL
- [x] fix URL creation - getFilePath
- [x] switching FRS client
- [ ] noodle over FluidPage
- [x] scaffold out data/nodes
- [ ] improving typing on dispatch
- [x] move FluidContainer
- [x] BIG POINT: move all files that we don't expect user to touch
  
## recipes

- [ ] write out recipes
- [ ] add DDS's
- [ ] add model functionality
- [ ] add actions
- [ ] add queries

## example

- [x] add two dice example
- [x] have button to add more dice to page
- [x] use sharedMap
- [x] create query to getDiceById
- [ ] create action for roll all dice
